name: This is workflow1
on: 
   schedule:
        - cron: "*/2 * * * *"
        
jobs:
     job1:
          runs-on: ubuntu-latest
          steps:
          - name: checkout code
            uses: actions/checkout@v2
          - name: print message
            run: echo 'Welcome to github action'


